funktional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты

non-funktional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Магазин — это SPA приложение, которое не перезагружает страницу
  - Сайт должен иметь мобильную версию

implicit: # неявные требования
  - Сайт должен автоматически определять язык интерфейса клиента и менять в соответствии с этим язык сайта 
  - Для оформления заказа необходима авторизация пользователя
  - После оформления заказа корзина должна очищаться автоматически
  - Пользователь должен иметь возможность указывать количество товара при добавлении в корзину
  - На сайте должна быть кнопка сброса всех фильтров
  - Корзина будет хранится в сессии браузера
